name: Deploy Chatter API

on:
  push:
    branches:
      - main

jobs:
  set-jwt:
    runs-on: ubuntu-latest
    env:
      Jwt__Key: ${{ secrets.JWT_KEY }}
      ConnectionStrings__DefaultConnection: ${{ secrets.PG_CONNECTION_STRING }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and run API
        run: |
          dotnet restore ./Server
          dotnet build ./Server